### PR TITLE
Credential retrieval

### PR DESCRIPTION
**Pull request by zamothh**
## Summary

This PR implements direct credential retrieval when using the command Get-PASAccountPassword :

_I want to reduce code in my scripts to directly have a PsCredential Object_
_I want increase security by avoiding credentials to get stored in memory_

## Test Plan
```
PS C:\> $PASAccount | Get-PASAccountPassword   -AsPsCredential

UserName                          Password
--------                          --------
Administrator System.Security.SecureString


PS C:\> $PASAccount | Get-PASAccountPassword   -AsPsCredential -UserName "LocalServer\administrator"

UserName                        Password
--------                        --------
LocalServer\administrator       System.Security.SecureString

```

### CODE REVIEW

**Comment by zamothh** [comment]
I'm not sure why I have a failing test ... if someone can explain me ....

**Comment by pspete** [comment]
Hi @zamothh 

Does the `ToSecureString()` meet your need?

`(Get-PASAccount -id 330_5 | Get-PASAccountPassword).ToSecureString()`

**Comment by zamothh** [comment]
Hi,

The securestring() object is not a PsCredential object.
Ideally, what I have done with other product up do now is :

$Cred = Get-PASAccount -search "computername" | Get-PASAccountPassword
-asPsCredential -username "myserver\administrator"
New-PSSession -ComputerName "myserver" -Credential $Cred
or
Invoke-restmethod -URI $URI -credential $cred

Directly having a credential object is very beneficial in coding automation

btw I work with Richard Eisenberger  & Charley Jacob for Cisco ... I know
that one of them told me he knew you ... not sure which one.

Thomas ***@***.***

**Comment by zamothh** [comment]
Hi again ...

There is something else that I directly saw, and that is API related,
rather than from PsPas.
When doing the authentication, the only return data is the API token... But
I guess each token has a lifespan, which is something I would like to have
as metadata.

This would allow the user to be able to see that the token has expired
before submitting the request.

Thanks for reading my mails :)
Thomas

**Comment by pspete** [comment]
> I'm not sure why I have a failing test ... if someone can explain me ....

The help files have not been updated with the description of the added parameters.
One of the modules tests ensures that each parameter is detailed in the help for the command.

**Comment by pspete** [comment]
> The securestring() object is not a PsCredential object.

Sure, but can be used to create a credential:
```powershell
$Credential=New-Object -TypeName System.Management.Automation.PSCredential `
 -ArgumentList "UserName", (Get-PASAccount -id 330_5 | Get-PASAccountPassword).ToSecureString()
```

**Review by pspete — CHANGES_REQUESTED** [review]
In line with the rest of the module, there is a strong preference for parametersets to be used to ensure values for required parameters are provided. This also makes the syntax detail generated by PlatyPS for the module's help text is more clear : https://pspas.pspete.dev/commands/Get-PASAccountPassword#syntax

**Comment by pspete** [comment]
@zamothh - it may also be an option to just add a `ToCredential()` method to [psPAS.CyberArk.Vault.Credential.Type.ps1xml](https://github.com/pspete/psPAS/blob/master/psPAS/xml/psPAS.CyberArk.Vault.Credential.Type.ps1xml) which accepts username as a parameter i.e.
```powershell
(Get-PASAccountPassword).ToCredential("SomeUser")
```
Thoughts?

**Comment by NathanielMaier** [comment]
> @zamothh - it may also be an option to just add a `ToCredential()` method to [psPAS.CyberArk.Vault.Credential.Type.ps1xml](https://github.com/pspete/psPAS/blob/master/psPAS/xml/psPAS.CyberArk.Vault.Credential.Type.ps1xml) which accepts username as a parameter i.e.
> 
> ```powershell
> (Get-PASAccountPassword).ToCredential("SomeUser")
> ```
> 
> Thoughts?

Most account objects have a username property already - anyway this `ToCredential()` function could default to that value if not overridden?

**Review by pspete — COMMENTED** [review]
@zamothh, Consider removing the `UserName` parameter and instead fetching the value assigned to the account in the vault

`$UserName = Get-PASAccount -id $AccountID | Select-Object -ExpandProperty Username`

**Comment by zamothh** [comment]
Should Work !

I am starting to look at this, and also at where and how to update the
documentation

Thomas

**Comment by zamothh** [comment]
I'm used to bitbucket, and I new to git hub ... not the same interface.

- I kept the Username filed as part of the Get-PASAccountPassword, and decided to expose it 
- I think I modified all xml files, but not sure
- I did my best to update the inline help file
- Added some examples in the root readme file, to that we have some examples
- Added the script method

I see that there is still some errors, I will try to look into that if I understand what needs to get done

**Comment by zamothh** [comment]
Hey, sorry for those multuple last moment push.
I won't modify the code anymore until you have a chance to review it. It looks much better than my initial commit.
Thomas

**Review by pspete — APPROVED** [review]

**Comment by pspete** [comment]
Thanks for the contribution @zamothh 👍🏼

**Comment by zamothh** [comment]
I'm helping myself first, in this particular case.
This is not the first powershell module I'm working on, and I am using
PlatyPs myself on one of my projects.

Is there any timeline for merging dev to master ?

**Comment by pspete** [comment]
> Is there any timeline for merging dev to master ?

Done via #368

**Pull request merged**
