### PR TITLE
:lock: Do not print out credentials

### LINKED ISSUE #131: Invoke-PASRestMethod prints credentials
## Expected Behaviour

Do not write out a password to a stream

## Current Behaviour

The password is printed out in the debug stream.  This can result in the password being written to file if the stream is being logged

## Possible Solution

Remove write-debug for REST parameters

## Steps to Reproduce (for bug reports)

1 . Set $DebugPreference = 'Continue'

2 . Run New-PASSession

## Sample Output

[DEBUG] [URI, https://mycyberark/PasswordVault/api/Auth/LDAP/Logon] [Method, POST] [Body, {
"username": "myusername",
"type": "LDAP",
"password": "mypassword"
}] [SessionVariable, PASSession] [UseDefaultCredentials, False] [ContentType, application/json] [UseBasicParsing, True]

## Context

Since this module is used to access/modify credential objects, I'd prefer to log all streams for auditing purposes.  This write-debug results in the user's credentials being written to log

### PR DESCRIPTION
**Pull request by karrth**
## Summary

This PR fixes/implements the following #131

_Explain the **motivation** for making this change. What existing problem does the pull request solve?_

Remove a write-debug that prints user's credentials

## Closes issues

Fixes #131 

Closes #131

### CODE REVIEW

**Comment by pspete** [comment]
Hi @karrth - I agree with your point of not capturing the password in the debug stream, however, that debug output can be useful for troubleshooting the request payload of other module functions.
Leaving `Invoke-PASRestMethod` as it is, would the same effect be achieved by adding `-Debug:false` to the invocation of `Invoke-PASRestMethod` in `New-PASSession`?

````powershell
$PASSession = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body -SessionVariable $SessionVariable -UseDefaultCredentials:($UseDefaultCredentials.IsPresent) -Debug:false

````

**Comment by DropBearHunta** [comment]
@pspete instead of using write-debug I would suggest removing this line and if needed use the psbreakpoint cmdlets which are not only more secure but additionally allow you to step through the script, allowing for a better debugging experience.

Not only does the `Set-PSBreakpoint` Cmdlets allows you to set a breakpoint on a particular line in a script, but allows for a breakpoint to be placed anytime a function or Variable is called.

In addition, while write-debug allows you to suspend the script and poke around, psbreakpoints allow you to look at the currently executing line and those around it, inspect the callstack, view all currently set variables, test logic within the context of  the command environment, and step into,over,and out of the script.

Furthermore, you don't need to leave these artifacts behind in the script as you are able to call `set-psbreakpoint` on an imported module and immediately begin debugging. 

I hope this helps, and allows you to merge this request as if anyone is logging the debugging stream (which can be done even if you set the debugging flag to $false) would receive plain text password within their log. Let me know if you have any questions!

**Comment by pspete** [comment]
@DropBearHunta - all perfectly valid; I personally have Breakpoints already configured which are used during development (and not included in the published files). 
My feedback relates to being able to easily request debug information from users of the module when issues are logged. 
The challenge is to determine if there is a middle ground, removing sensitive information from the debug stream, but maintaining the ability to simply collect supporting information for an issue.
Regardless of if this output is removed, the plaintext values will always be able to be revealed, using `Trace-Command` for instance.

**Comment by DropBearHunta** [comment]
This is True, however a Trace-Command could only be done from the system (and by the user) of which the command was run and therefor already has accessto the particular secret, my concern comes more into play when the debug stream is being logged, which can be done regardless of the $debugpreference variable. at that point you would have plain text passwords going to a file that could be accessed by anyone with access to the file. maybe instead we could remove the password property when writing to the debug stream? or perhaps sanitize it?

**Comment by pspete** [comment]
Now merged, and published to the PowerShell gallery as version 2.4.3

A solution for sanitised output of debug information may make its way into a future version.

Thanks for the contribution @karrth & for the comments @DropBearHunta

**Pull request merged**
